# This file was generated by GoReleaser. DO NOT EDIT.
cask "janusmcp" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c05884ea1f952168266a6df7073c83c2036a878d83fa96101c5a748ce66e8386"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76fd2b5e56626d223ec43292871573f893ef94141d2666398fecceba203a3f62"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1bc4b0ae855a9ceb95a627428065db92214580d88f6efac1499f169a8a25a1a5"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ae255c428049cfb58e758cca7f8b547c0abaff7969ab1b40382743c5823a73e"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_linux_arm64.tar.gz"
    end
  end

  name "janusmcp"
  desc "Local multi-account MCP broker — one endpoint, every account."
  homepage "https://github.com/bayway/janusmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "janusmcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/janusmcp"]
    end
  end

  # No zap stanza required

end
