# This file was generated by GoReleaser. DO NOT EDIT.
cask "janusmcp" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ff2a582d2384b69de51908688aa54664bcb9e647acedd6d9d074e68ff538369b"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e84c4191006cb0ab4bd630a9e76efa281e64928731ef58deded45738e47e837a"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b34570bf4fa9630638ac3fc55d1a97b73231610de08af331a204960896f65f5a"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b765356a8fe1fbd46a252cb044a10649d84dbec416c6bae23f0c941358e49dd"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_linux_arm64.tar.gz"
    end
  end

  name "janusmcp"
  desc "Local multi-account MCP broker — one endpoint, every account."
  homepage "https://github.com/bayway/janusmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "janusmcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/janusmcp"]
    end
  end

  # No zap stanza required

end
