# This file was generated by GoReleaser. DO NOT EDIT.
cask "janusmcp" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "9d4af29b732024b9692338a51a322a16f7050bca46d71c46243c7b804ccfdc7a"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "368b5e107756eb2a60239f578f01fa9e0299cd35e553ac2a7029b6e56a0b50cd"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd201643363923f8120ebe6b1529337700c93b0a7c213ec27257068d19a29dcd"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b77483921d4e4e6451eb653967501dbbce309e893430ec95c2ac6baa8ea4b88"
      url "https://github.com/bayway/janusmcp/releases/download/v#{version}/janusmcp_linux_arm64.tar.gz"
    end
  end

  name "janusmcp"
  desc "Multi-account tool broker for AI agents — CLI and MCP."
  homepage "https://github.com/bayway/janusmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "janusmcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/janusmcp"]
    end
  end

  # No zap stanza required

end
